# base image
FROM node:14-buster

# set working directory
WORKDIR /usr/src/app/data_visualization

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

RUN npm install react-scripts@3.4.3 -g --silent

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install --silent

# add app
#COPY . ./

# start app
CMD ["npm", "start"]

