FROM nginx:1.15.8-alpine

COPY ./templates/info ./usr/share/nginx/html
COPY ./templates/redoc ./usr/share/nginx/html/doc
COPY ./templates/upload ./usr/share/nginx/html/upload
COPY ./templates/impressum ./usr/share/nginx/html/impressum

RUN rm /etc/nginx/conf.d/default.conf
COPY /dev.conf /etc/nginx/conf.d