FROM nginx:1.15.8-alpine

COPY ./templates/en ./usr/share/nginx/html
COPY ./templates/en ./usr/share/nginx/html/en
COPY ./templates/de ./usr/share/nginx/html/de
COPY ./templates/redoc ./usr/share/nginx/html/doc

RUN rm /etc/nginx/conf.d/default.conf
COPY /dev.conf /etc/nginx/conf.d